### ISSUE TITLE
Strategy based on custom TradingView indicators

### ISSUE THREAD

**Issue by andriy2011** [cassandre-tech/cassandre-trading-bot#1047]
Greetings!
I'm sorry I this topic has been already address but I couldn't find any reference.

For example - I have my own custom TradingView indicator that triggers(vie webhook for ie) an event when to buy/sell.
Is it possible to integrate your bot with "external" strategy?

Thanks a lot!

**Comment by straumat** [comment]
@andriy2011 Hi  ! well, i don't include this option of i's your own java code that will make the bot so you can call any API or software from your bot
