### ISSUE TITLE
Discord invite link at website is outdated

### ISSUE THREAD

**Issue by buzz8year** [cassandre-tech/cassandre-trading-bot#1304]
**Release number**
Website https://cassandre.tech/

**Describe the bug**
Discord invite-link at website https://cassandre.tech/ is outdated.

**To Reproduce**
Website https://cassandre.tech/ main page invite-link button "Get in touch on Discord!".

**Expected behavior**
To be up-to-date.

**Comment by PCC2901** [comment]
to fix your trouble check this [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by straumat** [comment]
Sorry, i stopped the discord :(
