### ISSUE TITLE
Integration tests for Kraken

### ISSUE THREAD

**Issue by christophegrall** [cassandre-tech/cassandre-trading-bot#133]

**Comment by straumat** [comment]
Hi @christophegrall as Kraken has a sandbox, it seems possible ti implement ! I will take a look at it

**Comment by straumat** [comment]
btw @christophegrall integration tests are not required to use Cassandre with Kraken, it only has to be supported by Xchange.

**Comment by straumat** [comment]
Closed because it seems it's not necessary thanks to XChange tests
