### ISSUE TITLE
How to set up exchange agent?

### ISSUE THREAD

**Issue by a8585215** [cassandre-tech/cassandre-trading-bot#207]
exchange proxy cannot set

for example:

exchangeSpecification.setProxyHost("127.0.0.1");
exchangeSpecification.setProxyPort(4780);

**Comment by straumat** [comment]
Two parameters were added in the snapshot release : 
```
cassandre.trading.bot.exchange.proxyHost=127.0.0.1
cassandre.trading.bot.exchange.proxyPort=4780
```
