### ISSUE TITLE
Use several exchanges at the same time

### ISSUE THREAD

**Issue by dazito** [cassandre-tech/cassandre-trading-bot#261]
Hi, nice project :+1: 

Is it possible to use multiple exchanges at the same time? Something like, connect to exchange A, B and C and then apply the strategy to each exchange.
From what I could see in the code, this seems to not be possible. Am I right?

Any plans to add this feature?

**Comment by straumat** [comment]
Hello @dazito FOr the moment, it's not possible but we do it by running several trading bot on a docker server
