### ISSUE TITLE
Instructions is missing a step

### ISSUE THREAD

**Issue by JasperCiti** [cassandre-tech/cassandre-trading-bot#311]
**Describe the bug**
Followed the instructions on https://trading-bot.cassandre.tech/learn/quickstart but when I run my project I get the error:

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 2 of constructor in tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration required a bean of type 'tech.cassandre.trading.bot.repository.TradeRepository' that could not be found.
Action:
Consider defining a bean of type 'tech.cassandre.trading.bot.repository.TradeRepository' in your configuration.
```

**To Reproduce**
Follow the instructions on https://trading-bot.cassandre.tech/learn/quickstart

**Expected behavior**
To see something similar as the screenshot provided on https://trading-bot.cassandre.tech/learn/quickstart

**Screenshots**
See https://trading-bot.cassandre.tech/learn/quickstart

**Additional context**
In addition to the instructions provided by the website, I also created a basic class that implements TradeRepository and added that to the configuration, however I noticed that error message states that it is looking for a line **tech**.cassandre.trading.bot.repository.TradeRepository but all the other configurations are cassandre.trading.bot.repository.TradeRepository without the "tech" prefix. Not sure which one is correct without looking at the source code.

**Comment by JasperCiti** [comment]
Not sure why the configuration is necessary but after creating a spring `@Configuration` class that provide `@Beans` the above error message went away.

Now, I only get the error message:

```
***************************
APPLICATION FAILED TO START
***************************
Description:
Your strategy specifies a trading account that doesn't exist
Action:
Check your getTradeAccount(Set<AccountDTO> accounts) method as it returns an empty result
```

but I guess that was kind of expected as all my implementations are still default implementations that return empty objects.

It would have been nice if it the project could work out of the box even if it did nothing interesting yet as seen on the screenshots of the instructions.

**Comment by JasperCiti** [comment]
However, when I add my own configuration the "Check data reception" unit tests fails with "expected single matching bean but found 2: tradeRepository,getTradeRepository".

Could you please also add instruction how one is supposed to add repositories so that everything works per design?

**Comment by straumat** [comment]
Hello, can you provide the source code ? Seems this could happened if you choose for your project the same package than cassandre

**Comment by JasperCiti** [comment]
When I updated to cassandre-trading-bot-spring-boot-starter version 3.0.0 I was able to start the application without any beans or configuration classes.
