### ISSUE TITLE
Test can’t find the files tickers-*.tsv

### ISSUE THREAD

**Issue by awikatchikaen** [cassandre-tech/cassandre-trading-bot#329]
**Describe the bug**
Test can’t find the files tickers-*.tsv

**To Reproduce**
create project with gradle and import cassandre libraries. launch test

**Expected behavior**
Test OK

**Additional context**
the line 
final Resource[] resources = resolver.getResources("classpath:" + TICKERS_FILE_PREFIX + "*" + TICKERS_FILE_SUFFIX);
return empty array.

Seems that (with a ’*’):
final Resource[] resources = resolver.getResources("classpath*:" + TICKERS_FILE_PREFIX + "*" + TICKERS_FILE_SUFFIX);
works

**Comment by straumat** [comment]
Hi, did you import @Import(TickerFluxMock.class) in your unit tests ?
