### ISSUE TITLE
Exchange class name resolving not working for ConbasePro

### ISSUE THREAD

**Issue by kuceraf** [cassandre-tech/cassandre-trading-bot#397]
When setting configuration parameter in application.properties:
_cassandre.trading.bot.exchange.name=coinbasePro_
cassandre method **ExchangeAutoConfiguration#getExchangeClassName()** is not able to properly resolve exchange class name.

Resulting class name is:
_org.knowm.xchange.coinbasepro.CoinbaseproExchange_

Expected/required class name should be:
_org.knowm.xchange.coinbasepro.CoinbaseProExchange_
(please note the uppercase "P" letter)

Suggested solutions:
1. remove logic that lowercase the configured exchange name by default
**ExchangeAutoConfiguration#getExchangeClassName()**
_.concat(exchangeParameters.getName().substring(1).toLowerCase())_ 
2. add implementation that supports multi word names of exchanges in configuration
eg. some logic in getExchangeClassName() that transforms snake-case to cammelCase
it will allow to configure exchange name like this:
cassandre.trading.bot.exchange.name=coinbase-pro

let me know if I can help fixing this issue

**Comment by straumat** [comment]
Thx for your issue. I made a "temporary solution" as I think I will ask Xchange to add a meta-inf file or something like that to retrieve name of the exchange class of a jar; [The temporary fix is here](https://github.com/cassandre-tech/cassandre-trading-bot/blob/7e81d70e4bd8c6fa042b0522eae23f101630763e/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/configuration/ExchangeAutoConfiguration.java#L249)

I wasn't able to create a sandbox account as I already have an account :( and even to create a sandbox, they ask for passport and all.

For [Coinbase "classic"](https://mvnrepository.com/artifact/org.knowm.xchange/xchange-coinbase/5.0.4), I wrote the test [CoinbaseTest](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/spring-boot-starter/autoconfigure/src/test/java/tech/cassandre/trading/bot/test/configuration/exchange/CoinbaseTest.java), and managed to make it work but I have this message, maybe it's normal. : 
`No remote initialization implemented for Coinbase. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata`

I did the same thing for [Coinbase Pro](https://mvnrepository.com/artifact/org.knowm.xchange/xchange-coinbasepro/5.0.4) in [CoinbaseProTest](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/spring-boot-starter/autoconfigure/src/test/java/tech/cassandre/trading/bot/test/configuration/exchange/CoinbaseProTest.java), and I get a strange error `Illegal base64 character 2d` and it seems to occur when XChange class tries to retrieve the secret key. It's not null and I tried add a `.replace("\n", "")` and I still get the error.
Do you know if there is a special configuration to coinbase PRO ? Can you try my code with your credentials ?
For sure, the CLass problem is fixed

**Comment by straumat** [comment]
I have fixed the issue but with the wrong message, the fix is here : https://github.com/cassandre-tech/cassandre-trading-bot/commit/7e81d70e4bd8c6fa042b0522eae23f101630763e

**Comment by kuceraf** [comment]
Thanks for quick reaction and fix. 

I have try your fix (in 3.0.1-SNAPSHOT version) and it seems to be progress there (I can load the org.knowm.xchange.coinbasepro.CoinbaseProExchange as expected)

I also tried your new test CoinbaseProTest with my credentials as follows:
```
@DisplayName("Configuration - Exchange - Coinbase pro test")
@Configuration({
        @Property(key = PARAMETER_EXCHANGE_NAME, value = "coinbasePro"),
        @Property(key = PARAMETER_EXCHANGE_USERNAME, value = xxx),
        @Property(key = PARAMETER_EXCHANGE_PASSPHRASE, value = xxx),
        @Property(key = PARAMETER_EXCHANGE_KEY, value = xxx),
        @Property(key = PARAMETER_EXCHANGE_SECRET, value =  xxx)
})
@DirtiesContext(classMode = AFTER_EACH_TEST_METHOD)
public class CoinbaseProTest extends BaseTest {

    @Test
    @DisplayName("Check error messages")
    public void checkErrorMessages() {
        try {
            SpringApplication application = new SpringApplication(CassandreTradingBot.class);
            application.run();
            fail("Exception not raised");
        } catch (Exception e) {
            //assertTrue(e.getMessage().contains("(HTTP status code: 404)"));
        }
    }

}

```
The exchange instantiation was successful 
(no Illegal base64 character 2d error during ExchangeFactory.INSTANCE.createExchange(exchangeSpecification); )

But it fails with another error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Your strategy specifies a trading account that doesn't exist

Action:

Check your getTradeAccount(Set<AccountDTO> accounts) method as it returns an empty result - Account list : 6b969ef2-0cf2-41ab-9273-702b12f54586

```

**Comment by straumat** [comment]
Ok, this is not a but, it's normal !
You have to implement a method in the strategy to tell Cassandre which of your account is your trading one.

In your strategy, you should have something like this : 
```
@Override
	public Optional<AccountDTO> getTradeAccount(Set<AccountDTO> accounts) {
		return accounts.stream()
				.filter(a -> "6b969ef2-0cf2-41ab-9273-702b12f54586".equals(a.getName()))
				.findFirst();
	}
```

**Comment by straumat** [comment]
@kuceraf is it working now? Can I close this issue?

**Comment by kuceraf** [comment]
yes, it works. thank you
