### ISSUE TITLE
Wrong logging level at PositionFlux#saveValue(final PositionDTO newValue) method

### ISSUE THREAD

**Issue by kuceraf** [cassandre-tech/cassandre-trading-bot#419]
At PositionFlux#saveValue(final PositionDTO newValue) line 50 logs every method call as error. 
I believe it should be debug there...

**Comment by kuceraf** [comment]
I would create pull request with fix, but it seem I can not push to this repository...

**Comment by straumat** [comment]
Indeed! Thanks, it's fixed
