### ISSUE TITLE
TickerFluxMock not loading ticker files under Gradle

### ISSUE THREAD

**Issue by hmedkouri** [cassandre-tech/cassandre-trading-bot#432]
**Describe the bug**
Using gradle, TickerFluxMock fails to load ticker files.

**To Reproduce**
Using gradle instead of maven, **SimpleTa4jStrategyTest** of the [Backtest your strategy](https://trading-bot.cassandre.tech/learn/technical-analysis/backtest-your-trading-strategy) chapter fails with an NPE:

```
java.lang.NullPointerException
	at io.coinreach.trading.SimpleTa4jStrategyTest.gainTest(SimpleTa4jStrategyTest.java:55)
```

**Expected behavior**
**SimpleTa4jStrategyTest** should load the resources ticker file and list the positions.

**Additional context**
It's a great project. However, I prefer to use gradle instead of maven. It's very easy to convert the generated maven project into gradle's one. I believe the issue is due to the fact that gradle uses a different classpath for the test classes and resources.

I was able to fix this issue by overriding  **[getFilesToLoad()](https://github.com/cassandre-tech/cassandre-trading-bot/blob/508ed4ee700608bfbc46942beec320c45ad9c4ec/spring-boot-starter-test/autoconfigure/src/main/java/tech/cassandre/trading/bot/test/mock/TickerFluxMock.java#L122)** as follow:
```
@Override
    public List<Resource> getFilesToLoad() {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        try {
            final Resource[] resources = resolver.getResources("classpath*:" + TICKERS_FILE_PREFIX + "*" + TICKERS_FILE_SUFFIX);
            return Arrays.asList(resources);
        } catch (IOException e) {
            logger.error("TickerFluxMock encountered an error : " + e.getMessage());
        }
        return Collections.emptyList();
    }
```

As you can see I only added an "*" to `"classpath*:"` as per [PathMatchingResourcePatternResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/support/PathMatchingResourcePatternResolver.html) javadoc.

**Comment by straumat** [comment]
Hi ! Thx a lot, i will fix this ! The development branch is not in a good shape for the moment as I'm doing a big refactoring.

**Comment by hmedkouri** [comment]
Let me know I can create a PR, sorry I have just seen a similar issue but closed without any commit ([329](https://github.com/cassandre-tech/cassandre-trading-bot/issues/329)).
