### ISSUE TITLE
Unable to pass autoconfiguration, SQL exception

### ISSUE THREAD

**Issue by NarimanAB** [cassandre-tech/cassandre-trading-bot#458]
**Describe the bug**
00:10:14.439 [main] DEBUG org.hibernate.SQL - insert into exchange_accounts (id, created_on, account, exchange) values (default, ?, ?, ?)
00:10:14.443 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [TIMESTAMP] - [2021-02-24T00:10:14.303320200+01:00[Europe/Berlin]]
00:10:14.443 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [2] as [VARCHAR] - [cassandre.crypto.bot@gmail.com]
00:10:14.444 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [3] as [VARCHAR] - [org.knowm.xchange.gemini.v1.GeminiExchange]
00:10:14.445 [main] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: -10, SQLState: 23502
00:10:14.445 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - integrity constraint violation: NOT NULL check constraint; SYS_CT_10161 table: EXCHANGE_ACCOUNTS column: UPDATED_ON

**To Reproduce**
configure any exchange, start with empty db (spring.jpa.hibernate.ddl-auto=create)

**Expected behavior**
running application

**Screenshots**
none

**Additional context**
https://github.com/cassandre-tech/cassandre-trading-bot/blob/a1224370858fa1ad444247f48e7449d97a24d032/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/configuration/ExchangeAutoConfiguration.java#L214
null values in the not null field

**Comment by straumat** [comment]
Hi ! I am using liquidbase now. spring.jpa.hibernate.ddl-auto should be removed.

**Comment by NarimanAB** [comment]
oh... ok.

**Comment by straumat** [comment]
Thanks to liquidbase i hope it will be painless to migrate cassandre release for existing bots
