### ISSUE TITLE
Close open position

### ISSUE THREAD

**Issue by AllirionX** [cassandre-tech/cassandre-trading-bot#490]
The classes `GenericCassandreStrategy `and `PositionService` have a `createLongPosition` method. As the doc states: this will create a buy order.

However it is not currently possible to manually close a position. It would be convenient to have a `closeLongPosition(long positionId) ` method available that would take care of creating and sending the sell order and updating the position.

**Comment by straumat** [comment]
@AllirionX I'm sorry, in fact, it's more complicated than I thought because of multi-threading. I will first release the 4.1.0 this week and I will add this features next week.

**Comment by AllirionX** [comment]
@straumat I thought so. I would have done it if it was just firing the close order, but I could see their was concurrency management to do and that was too much for me to analyze. I still think it's a useful feature.

**Comment by straumat** [comment]
@AllirionX yes, multithreading is a bit complicated and I also wanted to add a field on `POSITIONS` table so we could tag positions that were forced to close. It could be useful for some statistics. Development is done.
