### ISSUE TITLE
Cannot backtest using ticker high and low

### ISSUE THREAD

**Issue by AllirionX** [cassandre-tech/cassandre-trading-bot#511]
The `TickerFluxMock.getTickersFromFile(final Resource file)` method does not populate the ticker's high and low.

Technical Indicators that use those variables (`org.ta4j.core.indicators.helpers.HighestValueIndicator`, `org.ta4j.core.indicators.StochasticOscillatorKIndicator`, etc.) cannot be backtested as the low and high price will remain 0.

**Comment by straumat** [comment]
@AllirionX Indeed ! i was putting them in bid & ask. now, big and ask are null... Maybe I should integrate other fields ?
