### ISSUE TITLE
result of the method getRequestedCurrencyPairs from  CassandreStrategyInterface should be cashed

### ISSUE THREAD

**Issue by Tempys** [cassandre-tech/cassandre-trading-bot#553]
The reason :
sometimes implementation of this method require external integration.
its not optimal run that method every time during  updating ticker  into `method  tickerUpdate`

```
    @Override
    public void tickerUpdate(final TickerDTO ticker) {
        // In multi strategies, all tickers are delivered to all strategies, so we filter in here.
        if (getRequestedCurrencyPairs().contains(ticker.getCurrencyPair())) {
            lastTickers.put(ticker.getCurrencyPair(), ticker);
            onTickerUpdate(ticker);
        }
    }

```

**Comment by straumat** [comment]
Hi, i need to call this each time as not all tickers should be distributed to all strategies

**Comment by straumat** [comment]
@Tempys 
To be more clear, certain users change dynamically the currency pairs they want. That's why we don't cch the reply.
Concerning your main problem, would it be ok for you to have in your strategy the list of supported currency pairs by the exchange ? It could be a static variable in the strategy class

**Comment by Tempys** [comment]
thanks got it

**Comment by straumat** [comment]
@Tempys would it solve your problem to have in your strategy the list of supported currency pairs by the exchange? It could be a static variable in the strategy class

**Comment by Tempys** [comment]
@straumat  i cashed my results its better approach then use static variable into strategy class
