### ISSUE TITLE
Allow position with leverage

### ISSUE THREAD

**Issue by awikatchikaen** [cassandre-tech/cassandre-trading-bot#565]
It's seems impossible to add a leverage on position even on platform which authorized it.
Why unauthorized this feature ?

**Comment by straumat** [comment]
@awikatchikaen I don't know how yet how leverage works. Can you tell me what you expect as behavior? Thx

**Comment by awikatchikaen** [comment]
When opening a position, i would like to set a leverage. 
It permit to place order, not with my assets, but with those lended by the platform. and so multiply gain (or loss)

**Comment by straumat** [comment]
@awikatchikaen which exchange are you using ?

**Comment by awikatchikaen** [comment]
I use kraken with currencies ETH-EUR for now

**Comment by straumat** [comment]
@awikatchikaen is there a case when the exchange can take a decision on your order?
Imagine I open a position and the exchange gets back its money ? How does it happened and how Cassandre could know the position is no more "valid" ?

**Comment by xblaatx** [comment]
> @awikatchikaen is there a case when the exchange can take a decision on your order?
> Imagine I open a position and the exchange gets back its money ? How does it happened and how Cassandre could know the position is no more "valid" ? 

You have to set a new order for returning the borrowed assets. When they price drops alot. And when your not able to payback the borrowed assets. Your account gets liquidated.
