### ISSUE TITLE
Force close position not working

### ISSUE THREAD

**Issue by awikatchikaen** [cassandre-tech/cassandre-trading-bot#568]
**Describe the bug**
I would like to close opened position when my strategy trigger shouldExit()

**To Reproduce**
have those line on your strategy
    @Override
    public void shouldExit() {
        getPositions().values()
                .stream()
                .filter(p -> p.getStatus().equals(PositionStatusDTO.OPENED))
                .forEach( p->{ System.out.println("exit "+p.getId()) ; p.setForceClosing(true);});
    }

**Expected behavior**
I expect all my position to be closed

**Comment by straumat** [comment]
@awikatchikaen did you wait a bit ? Because setForceClosing() just set a flag and the position will be closed when the next ticker arrives

**Comment by awikatchikaen** [comment]
Yes, I wait.
I'm in backtesting and dry mode 
multiple tickers arrives but positions are not closed.

**Comment by awikatchikaen** [comment]
ok, my bad forceclosing flag was not persist...
I use closePosition() Instead and it's working

Thank you
