### ISSUE TITLE
Update to ta4j 0.14

### ISSUE THREAD

**Issue by MarcDahlem** [cassandre-tech/cassandre-trading-bot#569]
This sunday, ta4j released a new version 0.14.
It would be great if cassandre updates to use this new version to profit from a lot of new improvements and indicators.

See https://github.com/ta4j/ta4j/releases/tag/0.14 for details

Hint:
 A lot of classes have been renamed in ta4j, especially "Order" --> "Trade", "Trade" --> "Position", and "PrecisionNum" --> "DecimalNum"

It would be great if this update results in a new cassandre release ;-)

**Comment by straumat** [comment]
@MarcDahlem Hi! I'm working on it https://github.com/cassandre-tech/cassandre-trading-bot/pull/571

**Comment by petrmac** [comment]
Done as a side effect of https://github.com/cassandre-tech/cassandre-trading-bot/pull/574

**Comment by straumat** [comment]
Done with merge of #574
