### ISSUE TITLE
Wrong implementation of method getTickers in MarketServiceXChangeImplementation class

### ISSUE THREAD

**Issue by Tempys** [cassandre-tech/cassandre-trading-bot#577]
Found the next issue

```
 @Override
    public final Set<TickerDTO> getTickers(final Set<CurrencyPairDTO> currencyPairs) {
       *** avoid **************
            logger.debug("MarketService - Getting tickers for {} currency pairs", currencyPairs.size());
** avoid ******
    }
```

despite of  input final Set<CurrencyPairDTO> currencyPairs has size 1 .
final List<Ticker> tickers = marketDataService.getTickers(params); return 1428 items

**Comment by straumat** [comment]
Can you explain me a bit more the problem please ? I'm not sure to understand

**Comment by Tempys** [comment]
input parameter final `Set<CurrencyPairDTO> currencyPairs `c contain only 1 element

final List tickers = marketDataService.getTickers(params); return 1428 items
but in list we can see 1428 currencies trades

**Comment by straumat** [comment]
Are you using `4.2.2-SNAPSHOT`? 
In the last release, we only add the currencyPairs passed as parameters.

**Comment by straumat** [comment]
@Tempys can't reproduce this issue, can you tell me more ?

**Comment by Tempys** [comment]
i use binance
reproducing is very simple 
put debug pointer on the method marketService.getTickers(currencyPairs1); and see return size which will not equals to input curr size .

**Comment by straumat** [comment]
@Tempys I think it's fixed. Can you take a look please ? with the 5.0.0 SNAPSHOT
