### ISSUE TITLE
Error in cancelOrder in TradeService class

### ISSUE THREAD

**Issue by Tempys** [cassandre-tech/cassandre-trading-bot#584]
when i tried to loanch method 
```
    /**
     * Cancel order.
     *
     * @param orderId order id
     * @return true if cancelled
     */
    boolean cancelOrder(String orderId);
```

in TradeService

i got the next error 

`2021-05-04 20:45:31,536 ERROR [boundedElastic-5] tech.cassandre.trading.bot.service.xchange.TradeServiceXChangeImplementation: TradeService - Error canceling order 130285696 : You need to provide the currency pair to cancel an order.`

**Comment by straumat** [comment]
@Tempys thx! It works without currency pair on kucoin ! Which exchange are you using ? still Binance ?

**Comment by Tempys** [comment]
@straumat yes im using binance

**Comment by Tempys** [comment]
@straumat should be additional method
  public boolean cancelOrder(CancelOrderParams params) throws IOException {

**Comment by Tempys** [comment]
also that problem required a specific implementation ((((

**Comment by dstibbe** [comment]
But that would mean you would have the call one or the other strategy based on the exchange being used. 
Wouldn't it be better to always provide the currency pair?

**Comment by straumat** [comment]
@dstibbe I will call the method with the currency pair, and my integration tests will check if it still works with an exchange not supporting this parameter.

I already do that [here](https://github.com/cassandre-tech/cassandre-trading-bot/blob/88607fe6c97a75fd6b233d24dbf2cd3c12829111/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/xchange/TradeServiceXChangeImplementation.java#L258). Some exchanges requires currency pair as a parameter to trieve trades

**Comment by straumat** [comment]
Geez. More complicated than thought... BinanceCancelOrderParams has to be created so It forces me to add xchange-binance to the main project which is really not a good idea :(

**Comment by dstibbe** [comment]
But why retrieve the currency pair from the order repos if the strategy can simply provide it ? 

And regarding xchange-binance: just implement the CancelOrderByCurrencyPair and CancelOrderByIdParams interfaces

**Comment by straumat** [comment]
In cassandre, i don't have a dependency for any exchange library except xchange-core. And it seems I need to fulfill BinanceCancelOrderParams which forces me to add xchange-binance which is not clean

**Comment by dstibbe** [comment]
No. binance xchange implementation just checks for CancelOrderByCurrencyPair and CancelOrderByIdParams...
implement these interfaces and no extra dependency is required

**Comment by Tempys** [comment]
yeah ((
looks you need to move that on strategy level as i do

that code is working for me 
CancelOrderParams cancelOrderParams = new BinanceCancelOrderParams(currencyPair,buyOrderId);
                            getTradeService().cancelOrder(cancelOrderParams);

**Comment by straumat** [comment]
@dstibbe but a BinanceCancelOrderParams has to be instantiated no?

**Comment by dstibbe** [comment]
NO :P

**Comment by dstibbe** [comment]
Just create a new class :
`
public class BinanceCancelOrderParams implements CancelOrderByIdParams, CancelOrderByCurrencyPair {
    private final String orderId;
    private final CurrencyPair pair;

    public IdAndOrderCancelOrderParams(CurrencyPair pair, String orderId) {
        this.pair = pair;
        this.orderId = orderId;
    }

    public CurrencyPair getCurrencyPair() {
        return this.pair;
    }

    public String getOrderId() {
        return this.orderId;
    }
}`

and use that

**Comment by Tempys** [comment]
@dstibbe its not only binance specific other exchange can require other parameters 

so about that should functionality should  be responsible strategy and not bot

**Comment by dstibbe** [comment]
And I would just change the signature of cassandre's TradeService cancelOrder to : `public final boolean cancelOrder(final String orderId, CurrencyPair currency)` 
and have the strategies call cancelOrder with the currency .
Instead of pulling it out of the order repos

**Comment by dstibbe** [comment]
@Tempys  yes, it is not only binance specific, so I would say have Cassandre's tradeService always call the xchange tradeservice with a currencypair

**Comment by dstibbe** [comment]
If you don't, you are gonna have to make logic based on which exchange you are communicating with

**Comment by dstibbe** [comment]
And I just noticed ,  the class I was suggesting to implement already exists ! :D
Use `org.knowm.xchange.service.trade.DefaultCancelOrderByCurrencyPairAndIdParams`  instead of BinanceCancelOrderParams

**Comment by dstibbe** [comment]
@Tempys   regarding cancel orders on other exchanges: it seems Xchange has narrowed it down to 4 params:
* orderId
* currencyPair
* orderType
* userReference

based on the existing interface
