### ISSUE TITLE
CPU at 100%

### ISSUE THREAD

**Issue by dev590t** [cassandre-tech/cassandre-trading-bot#588]
**Describe the bug**
CPU increase to 88% to 100% when I run the test

**To Reproduce**
Create the project:
```
mvn -B archetype:generate -DarchetypeGroupId=tech.cassandre.trading.bot \
-DarchetypeArtifactId=cassandre-trading-bot-spring-boot-starter-basic-ta4j-archetype \
-DarchetypeVersion=4.2.1 \
-DgroupId=com.example \
-DartifactId=ta4j-strategy \
-Dversion=1.0-SNAPSHOT \
-Dpackage=com.example
```
Run `mvn test`
CPU is around 88% and 100%

**Environement**
```
Apache Maven 3.6.1
Java version: 11.0.11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.3-gnu", arch: "amd64", family: "unix"
```

**Comment by straumat** [comment]
@dev590t Hi, it's what i expect in fact :) Cassandre is multithread so it should eat every available resource :)

**Comment by dev590t** [comment]
Hi @straumat , so cassandre need a enhancement about that. 
The strategy is very basic. Consume 100% CPU for a basic strategy isn't really preferable.

Cassandre consumes 100% CPU, but the test of the strategy take much time. The users prefer wait 5 second max for a simple strategy like that. We like have quickly a feedback after modify a strategy. But the test take one minute for me. 
Should also a enhancement about that. I see exist already a ticket #282 about the speed of test. The ticket is closed, but the speed problem still exists. Maybe the ticket isn't about this issue.
I have also open a new issue  #606 about this problem also?

**Comment by straumat** [comment]
Closing as tests speed will be treated with #606
