### ISSUE TITLE
[Question] Change ticking speed during tests?

### ISSUE THREAD

**Issue by lwitzani** [cassandre-tech/cassandre-trading-bot#616]
Hi :) 
i searched for my problem but could not find anything. 

Is there a fixed 1 second delay between ticks during test execution using TickerFluxMock? Are there some application properties that could change the behavior during tests? I mean, if i have a test file with 1500 lines of ticks, i do not want to wait 1500 seconds till i know the result of my strategy (?). 
Can't it run much much faster than one tick per second?
Thanks for the answer. 
Best regards,
Lukas

**Comment by straumat** [comment]
@lwitzani Hi, i'm sorry for the moment, i wan't able to make it faster as tickers have to be proceed by all thread. I'm currently working on a solution but it's not at all easy :(
