### ISSUE TITLE
Invalid order: not enough tradable balance on BitFinex exchange

### ISSUE THREAD

**Issue by fernandoscaliaviooh** [cassandre-tech/cassandre-trading-bot#618]
**Is your feature request related to a problem? Please describe.**
While opening an order, I am receiving the message "Invalid order: not enough tradable balance". 
I have balance on the Exchange wallet and on Margin wallet.
I read in the forums that the order type must be "exchange limit" instead of only "limit" order.

**Describe the solution you'd like**
That would be good to have a constructor for the orders where we can pass the order type following the Enum from knowm lib: org.knowm.xchange.bitfinex.v1.BitfinexOrderType

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by straumat** [comment]
@fernandoscaliaviooh do you use our position system or only the order ? 
If it's only for order, I can create a new method for this special kind.
But tell me, do you have the error because you want to use your margin account ?

**Comment by fernandoscaliaviooh** [comment]
@straumat the error is happening when I am trying to call `createLongPosition` and `createShortPosition` methods (When shouldEnter() is triggered).
So when I am opening a position, I have no option to choose the margin or exchange wallets, so I have added funds to both and even though the above methods to create position is not working.

I am not sure I answered you question properly, but please let me know if I can help with more information.

**Comment by straumat** [comment]
Sorry for the delay, I will create an account on bitfinex as they support a kind of sandbox. So I could write integration tests : https://support.bitfinex.com/hc/en-us/articles/900001525006-Paper-Trading-test-learn-and-simulate-trading-strategies-

**Comment by straumat** [comment]
@fernandoscaliaviooh Hi. Did you try to use v2 of bitfixnet instead of v1. I haven't seend BitfinexOrderType in v2 maybe it's no more useful?
