### ISSUE TITLE
Extend Cassandre for Equities

### ISSUE THREAD

**Issue by kgoderis** [cassandre-tech/cassandre-trading-bot#673]
@straumat I sent you an email wrt the idea/question to extend Cassandra to support other instruments as well. I have studied your source code in the meantime, and it seems very doable with limited effort.

**Comment by straumat** [comment]
@kgoderis Hi ! Your email was in SPAM :) I reply to ur email and close this issue !

**Comment by kgoderis** [comment]
@straumat No prob. Btw, my latest reply might sit there as well
