### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by straumat** [cassandre-tech/cassandre-trading-bot#680]
- [x] Creates the spring boot starter.
- [ ] Add authentication.
- [ ] Get strategy (list/unique).
- [ ] Get positions (list/by stategy/unique).
- [ ] Get gains.

**Comment by nedimAT** [comment]
Hello, as this is spring boot, i think this information should be visible in the actuator and configurable (true/false) if you want to expose it.

**Comment by straumat** [comment]
@nedimAT yes! Rest API is still an early stage for now but I will follow your advice

**Comment by nedimAT** [comment]
thanks for the quick reply, if possible i would like to help with this

**Comment by straumat** [comment]
@nedimAT for informatin, I nearly finished the graphQL API in 5.0.4-SNAPSHOT

**Comment by straumat** [comment]
Removing it temporaly. To see if graphQL Api is enough
