### ISSUE TITLE
[Kucoin Sandbox] Sample application startup fails due to http error 403 thrown during Exchange initialization

### ISSUE THREAD

**Issue by lucarosellini** [cassandre-tech/cassandre-trading-bot#686]
**Release number**
5.0.1

**Describe the bug**
I get an http error 403 with response body `{"code":"400007","msg":"Access denied, require more permission."}` from Kucoin Sandbox while calling the endpoint https://openapi-sandbox.kucoin.com/api/v1/base-fee at Exchange initialization during the sample application startup.
The Kucoin Sandbox account used is brand new.

**To Reproduce**
- Create a new project using the cassandre 5.0.1 artifact
- Create a new API on Kucoin Sandbox as described in https://trading-bot.cassandre.tech/ressources/how-tos/how-to-create-a-kucoin-account.html#get-api-credentials
  - permissions enabled: 'General' and 'Trade'
- Configure API passphrase, key and secret in application.properties (I double checked all the information and they are OK).
- Startup the Sample application.
- A 403 is error is returned calling the endpoint https://openapi-sandbox.kucoin.com/api/v1/base-fee (see attached logs below)

**Expected behavior**
The application should start up correctly and the sample strategy should start to run.

**Screenshots**

**Additional context**
Attaching the full application startup log with logging level for 'si.mazi.rescu' set to TRACE (API Information hidden).

[cassandre-app-startup.log](https://github.com/cassandre-tech/cassandre-trading-bot/files/6885307/cassandre-app-startup.log)

**Comment by straumat** [comment]
Hi @lucarosellini there is a problem with Kucoin Sandbox server. I send them a message to ask them to fix it but no reply yet.
For information I have a bot running 5.0.1 with Kucoin classic and it works perfectly.
Kucoin sandbox is quite often down :(

**Comment by lucarosellini** [comment]
Thanks a lot for the info @straumat, I'll keep trying from time to time to check whether or not kucoin fixed the issue.

**Comment by straumat** [comment]
@lucarosellini I will keep you updated if they give a reply to my email

**Comment by straumat** [comment]
@lucarosellini for information, I run a strategy with positions (short and long) with 5.0.1 for 3 weeks with Kucoin and there was no problem.

**Comment by straumat** [comment]
@lucarosellini I'm on holiday so i will see that later but if you have time, they asked me to connect to to them throw Instagram:
`Sorry for the late reply, please contact us through telegram to offer you with more convenient service:
@KuCoin_API_Team01`

**Comment by straumat** [comment]
They have a problem with the sandbox API and it will last some time... 😥
![Screenshot_20210809-113733_Telegram.jpg](https://user-images.githubusercontent.com/536498/128687199-606e7675-9247-4df3-b17d-5265a16710db.jpg)

**Comment by 331520** [comment]
HI @straumat!
HI @straumat!
The issue still exists for me. On 5.0.3 and 5.0.1, it doesn't matter.  I try to connect to https://sandbox.kucoin.com/ but after executing mvn spring-boot:run always get an error 
=========================
00:41:48 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration': Invocation of init method failed; nested exception is tech.cassandre.trading.bot.util.exception.ConfigurationException: Unknown configuration error: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 403
==========================
Could you please advise anything in this case? Thanks in advance, 
Alex

**Comment by 331520** [comment]
HI @straumat!

The issue still exists for me. On 5.0.3 and 5.0.1, it doesn't matter.  I try to connect to https://sandbox.kucoin.com/ but after executing mvn spring-boot:run always get an error 
=========================
00:41:48 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration': Invocation of init method failed; nested exception is tech.cassandre.trading.bot.util.exception.ConfigurationException: Unknown configuration error: si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 403
==========================
Could you please advise anything in this case? Thanks in advance, 
Alex

**Comment by straumat** [comment]
@331520 Yes. Kucoin did not update the sandbox yet. But it works perfectly in kucoin production... 
For the moment, I test with drymode set to true and I run in production with sandbox to false

**Comment by 331520** [comment]
Thank you @straumat

**Comment by straumat** [comment]
2 December - Still got the error. If you know an exchange who have a sandbox, I would be glad to change the default account in cassandre.

**Comment by lucarosellini** [comment]
@straumat thanks for the update. Bybit does have a very nice testnet, but unfortunately it's not yet supported by XChange.

**Comment by straumat** [comment]
@lucarosellini thx ! I will keep an eye on Xchange support for Bybit

**Comment by straumat** [comment]
I had a chat two days ago with Kucoin API support team, they say they will update the sandbox within two weeks. Hope it will work. ![kucoin_conversation](https://user-images.githubusercontent.com/536498/147669117-94728e80-8fa7-4d81-8bcd-a7e63d8a86ea.png)

**Comment by straumat** [comment]
Testing today, I get a new error: 401. After logging to my sandbox account I created a new API access:
```
cassandre.trading.bot.exchange.driver-class-name=kucoin
cassandre.trading.bot.exchange.username=kucoin.cassandre.test@gmail.com
cassandre.trading.bot.exchange.passphrase=cassandre
cassandre.trading.bot.exchange.key=61d0c8a041a5330001d0d59c
cassandre.trading.bot.exchange.secret=79edb229-a9c8-449d-a476-04689eaf376b
``` 

When I try to connect, I get this new error (with 5.0.6):
``` 
java.lang.NullPointerException
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
	at org.knowm.xchange.kucoin.KucoinAdapters.adaptCurrencyMetaData(KucoinAdapters.java:172)
	at org.knowm.xchange.kucoin.KucoinAdapters.adaptMetadata(KucoinAdapters.java:115)
	at org.knowm.xchange.kucoin.KucoinExchange.remoteInit(KucoinExchange.java:102)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
	at org.knowm.xchange.kucoin.KucoinExchange.applySpecification(KucoinExchange.java:53)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
	at tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration.configure(ExchangeAutoConfiguration.java:150)
``` 

I need some time to go check in the XChange library.

**Comment by straumat** [comment]
The error comes from the fact that, for USDN, kucoin returns null values for `getWithdrawalMinFee` and `getWithdrawalMinSize`.

I created a pull request for XChange:  https://github.com/knowm/XChange/pull/4376

**Comment by straumat** [comment]
The problem is now solved.

In `src/main/resources/application.properties`, change those parameters:
```
cassandre.trading.bot.exchange.driver-class-name=kucoin
cassandre.trading.bot.exchange.username=kucoin.cassandre.test@gmail.com
cassandre.trading.bot.exchange.passphrase=cassandre
cassandre.trading.bot.exchange.key=61d0c8a041a5330001d0d59c
cassandre.trading.bot.exchange.secret=79edb229-a9c8-449d-a476-04689eaf376b
#
# Modes
cassandre.trading.bot.exchange.modes.sandbox=true
cassandre.trading.bot.exchange.modes.dry=false
```

If Xchange did not close my [pull request](https://github.com/knowm/XChange/pull/4376), you have to download my [XChange release](https://github.com/straumat/XChange) and build it with: `mvn clean install -Dgpg.skip -Dmaven.test.skip=true`.

Then in your pom.xml, set this release:
```
<dependency>
   <groupId>org.knowm.xchange</groupId>
   <artifactId>xchange-kucoin</artifactId>
   <version>5.0.13-SNAPSHOT</version>
</dependency>
```

Yout bot should start now on the sandbox !
