### ISSUE TITLE
Updating DurationBarAggregator to sync the bar start and end times to candle start and end time of the Exchange

### ISSUE THREAD

**Issue by mobilepro** [cassandre-tech/cassandre-trading-bot#716]
Consider 
`cassandre.trading.bot.exchange.rates.ticker 
`
and 
`  @Override
    public Duration getDelayBetweenTwoBars() {
        // Delay between two bars.
        return Duration.ofMinutes(1);
    }`

May not trigger and start the scheduler at exactly when a Minute end/start and based on the getDelayBetweenTwoBars()
for example if the first trigger happens at 8:05:29 AM then the first bar creation will happen at 8:06:29 AM and next at 8:07:29 AM etc...
But the real charts from Exchange usually aligned to exact start of a minute/hour

Can the `tech.cassandre.trading.bot.util.ta4j.BarContext#isAfter ` be modified to generate bars at exact minutes 8:05:00 AM, 8:06:00 AM, 8:07:00 AM...to match the bar start and end time of the Exchange? 

It could be easy fix to handle minutes scenarios 1M,2M,5M,15M,30M, scenarios. 
But hours scenarios like 1H, 4H etc may need more considerations.

**Comment by mobilepro** [comment]
Code suggestion

**_Properties_**
`cassandre.trading.bot.matchexchangechart=true`

_`DurationBarAggregator`_


```
    @Value("cassandre.trading.bot.matchexchangechart")
    boolean matchExchangeChart;
```

```
 @Override
    public void update(final ZonedDateTime timestamp, final Number close, final Number high, final Number low,
                       final Number volume) {
        if (ctx == null && canStartBarContext(timestamp)) {
            ctx = new BarContext(duration, timestamp, low, high, 0, close, volume);
        } else if (ctx.isAfter(timestamp)) {
            // we have new bar starting - emit current ctx
            sink.next(new BaseBar(duration, ctx.getEndTime(), ctx.getOpen(), ctx.getHigh(),
                    ctx.getLow(), ctx.getClose(), ctx.getVolume()));
            // take the close and start counting new context
            ctx = new BarContext(duration, timestamp, low, high, ctx.getClose(), close, volume);
        } else if (ctx != null) {
            ctx.update(low, high, close, volume);
        }
    }
```

```
private boolean canStartBarContext(final ZonedDateTime timestamp) {

        boolean startBarContext = true;
        if (matchExchangeChart) {
            int durationInSec = (int) duration.getSeconds();
            int durationInMin = durationInSec / 60;

            boolean isMinuteStart = timestamp.getSecond() % 60 == 0;

            switch (durationInSec) {
                case 60:
                    startBarContext = isMinuteStart;
                    break;
                case 120:
                case 300:
                case 900:
                case 1800:
                    startBarContext = isMinuteStart && timestamp.getMinute() % durationInMin == 0;
                    break;
            }
        }
        return startBarContext;
    }
```

**Comment by straumat** [comment]
@mobilepro thx for your suggestion. But if I did understand well what you want, it doesn't guarantee that the ticker i receive if a round time ? i could ask at 00:05:00 for a ticker but the server may reply with a ticker timed at 00:05:02 ?

**Comment by mobilepro** [comment]
Yes, You are right,
I had to add some more conditions but this goal is still not 100% achievable has to explorer a bit more.


**ScheduleAutoConfiguration**
`  
    public static final int ONE = 1;

     /** Is TickerStarted. */
    private boolean tickerStarted = false;`

`    /**
     * Recurrent calls to the ticker flux.
     */
    @Scheduled(initialDelay = START_DELAY_IN_MILLISECONDS, fixedDelay = 1)
    public void tickerFluxUpdate() {

        **if (!tickerStarted && LocalTime.now().getSecond() == ONE) { // Observation was it was trying to get 0sec Ticker when 1sec
            logger.info("Start Ticker scheduler First at {}", LocalTime.now());
            tickerStarted =  true;
        }**

        if (tickerStarted && enabled.get()) {
            logger.info("Triggered scheduler at {}", LocalTime.now());
            tickerFlux.update();
        }
`


**DurationBarAggregator**

`    /**
     * matchExchangeChart.
     */
    @Value("cassandre.trading.bot.matchexchangechart:true")
    private boolean matchExchangeChart = true;

    /**
     * ONE_MIN.
     */
    public static final int ONE_MIN = 60;
    /**
     * TWO_MIN.
     */
    static final int TWO_MIN = 120;
    /**
     * FIFTEEN_MIN.
     */
    static final int FIFTEEN_MIN = 900;
    /**
     * FIVE_MIN.
     */
    static final int FIVE_MIN = 300;
    /**
     * THIRTY_MIN.
     */
    static final int THIRTY_MIN = 1800;`

`    public void update(final ZonedDateTime timestamp, final Number close, final Number high, final Number low,
                       final Number volume) {
        if (ctx == null && canStartBarContext(timestamp)) {
            ctx = new BarContext(duration, timestamp, low, high, 0, close, volume);
        } else if (ctx != null && ctx.isAfter(timestamp)) {
            // we have new bar starting - emit current ctx
            sink.next(new BaseBar(duration, ctx.getEndTime(), ctx.getOpen(), ctx.getHigh(),
                    ctx.getLow(), ctx.getClose(), ctx.getVolume()));
            // take the close and start counting new context
            ctx = new BarContext(duration, timestamp, low, high, ctx.getClose(), close, volume);
        } else if (ctx != null) {
            ctx.update(low, high, close, volume);
        }
    }`
`    /**
     *
     * @param timestamp
     * @return startBarContext
     */
    private boolean canStartBarContext(final ZonedDateTime timestamp) {

        log.info("matchExchangeChart {}", matchExchangeChart);
        boolean startBarContext = true;
        if (matchExchangeChart) {
            int durationInSec = (int) duration.getSeconds();
            int durationInMin = durationInSec / ONE_MIN;
            log.info("Ticker timestamp {}", timestamp);

            boolean isMinuteStart = timestamp.getSecond() % ONE_MIN == 0;

            switch (durationInSec) {
                case ONE_MIN:
                    startBarContext = isMinuteStart;
                    break;
                case TWO_MIN:
                case FIVE_MIN:
                case FIFTEEN_MIN:
                case THIRTY_MIN:
                    startBarContext = isMinuteStart && timestamp.getMinute() % durationInMin == 0;
                    break;
                default:
                    break;
            }
        }
        log.info("startBarContext return {}", startBarContext);
        return startBarContext;
    }`
