### ISSUE TITLE
[Binance] Too much request weight used when sandbox=true

### ISSUE THREAD

**Issue by Maczekpl93** [cassandre-tech/cassandre-trading-bot#737]
**Release number**
5.0.3

**Describe the bug**
I have basic strategy (TA4J) for one currency pair BTC,USDT and i get "Too much request weight used" after few second from start

**To Reproduce**
Create TA4J Strategy for BTC,USDT crypto pair. Set sandbox true. Start bot

**Expected behavior**
Bot should work stable

**Screenshots**

**Additional context**

I try few diffrent rates configuration but it's nothing changed

**Comment by straumat** [comment]
Hi, I think Binance doesn't have a sandbox. So you shoult set the parameter to false. My binance bot work greats in production with those parameters:
```
# Exchange API calls rates (ms or standard ISO 8601 duration like 'PT5S').
cassandre.trading.bot.exchange.rates.account=PT30S
cassandre.trading.bot.exchange.rates.ticker=PT30S
cassandre.trading.bot.exchange.rates.trade=PT30S
```
