### ISSUE TITLE
Don't know why ctb call `CassandreStrategyInterface#getRequestedCurrencyPairs() quite a lot

### ISSUE THREAD

**Issue by huahouye** [cassandre-tech/cassandre-trading-bot#738]
**Release number**
5.0.3

**Describe the bug**
calling `getRequestedCurrencyPairs()` method too frequently. I use database to store my project configurations. and I want to load them in `getRequestedCurrencyPairs()` method, but don't know why ctb calling this method like this, it seems like a bug.

**To Reproduce**

```
mvn archetype:generate \
-DarchetypeGroupId=tech.cassandre.trading.bot \
-DarchetypeArtifactId=cassandre-trading-bot-spring-boot-starter-basic-archetype \
-DarchetypeVersion=5.0.3
```

add log info for getRequestedCurrencyPairs() method in SimpleStrategy class. then start ctb.

```
@Override
public Set<CurrencyPairDTO> getRequestedCurrencyPairs() {
	// We only ask about ETC/BTC (Base currency : BTC / Quote currency : USDT).
	logger.debug("calling getRequestedCurrencyPairs()..."); // add log info here, it will print a lot of logs when schedule gets triggered
	return Set.of(new CurrencyPairDTO(BTC, USDT));
}
```

**Comment by straumat** [comment]
@huahouye Some users change the requested currency pairs dynamically. So every time Cassandre is about to ask tickers to the exchange, I have to call every strategy and ask what currency pairs they want. I don't like it but seems lots of users need this feature. Do you see what I mean ?

**Comment by huahouye** [comment]
@straumat  thanks for your quick reply. yes, I understand what say. I've just read that code. I will use memory cahe for doing that. Maybe it should be mentioned in the quickstart documentation.

And if we take  [getRequestedCurrencyPairs()](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/strategy/GenericCassandreStrategy.java#L187) outside stream pipeline, it will work too. we don't have to get pairs for every element to be filtered.

**Comment by straumat** [comment]
@huahouye
- You can have several strategies requesting several currency pairs. 
- Before calling the server, I have to ask all strategies what they want right now.
- Once the batch retrieved all replis, it sends them to all strategies 
- From the server reply, every strategy filter to retrieve only the currency pairs it wants

**Comment by huahouye** [comment]
@straumat yes, I understand that.

what i want to say is that:

// before in GenericCassandreStrategy
```
@Override
public void tickersUpdates(final Set<TickerDTO> tickers) {
    // We only retrieve the tickers requested by the strategy.
    final Map<CurrencyPairDTO, TickerDTO> tickersUpdates = tickers.stream()
            .filter(tickerDTO -> getRequestedCurrencyPairs().contains(tickerDTO.getCurrencyPair()))
            // We update the values of the last tickers that can be found in the strategy.
            .peek(tickerDTO -> lastTickers.put(tickerDTO.getCurrencyPair(), tickerDTO))
            .collect(Collectors.toMap(TickerDTO::getCurrencyPair, Function.identity(), (id, value) -> id, LinkedHashMap::new));

    // We update the positions with tickers.
    updatePositionsWithTickersUpdates(tickersUpdates);

    // We notify the strategy.
    onTickersUpdates(tickersUpdates);
}
```

// after in GenericCassandreStrategy
```
@Override
public void tickersUpdates(final Set<TickerDTO> tickers) {
    // We only retrieve the tickers requested by the strategy.
   var wantedPairs = getRequestedCurrencyPairs(); // take this line outside there, otherwise how many tickers size, it will be excute how many times.
    final Map<CurrencyPairDTO, TickerDTO> tickersUpdates = tickers.stream()
            .filter(tickerDTO -> wantedPairs.contains(tickerDTO.getCurrencyPair()))
            // We update the values of the last tickers that can be found in the strategy.
            .peek(tickerDTO -> lastTickers.put(tickerDTO.getCurrencyPair(), tickerDTO))
            .collect(Collectors.toMap(TickerDTO::getCurrencyPair, Function.identity(), (id, value) -> id, LinkedHashMap::new));

    // We update the positions with tickers.
    updatePositionsWithTickersUpdates(tickersUpdates);

    // We notify the strategy.
    onTickersUpdates(tickersUpdates);
}
```

right?

**Comment by straumat** [comment]
@huahouye you mean I could cache the result of `getRequestedCurrencyPairs() `instead of calling it for every tickers. This way, it will not call a possibly complex business logic in `getRequestedCurrencyPairs() ` ?

**Comment by huahouye** [comment]
@straumat that is Exactly what i mean. in my opinion `getRequestedCurrencyPairs()`  executed once in `tickersUpdates(final Set<TickerDTO> tickers) ` is fine,  When next `tickersUpdates` event arrives, it will be executed again, it is enough for me when I waiting my new configuration become effective.

**Comment by straumat** [comment]
@huahouye You are right. I will implement this.
