### ISSUE TITLE
Is it possible to use WebSocket instead of polling, for tickerUpdates?

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#792]
I was thinking on running several bot on the same IP, as the rate limits is per IP, I will probably hit that limit. As the WebSocket is the recommended way for continuous 'live' requests, I was wondering if it's possible to do that _(for those exchanges that supports webSockets)_

**Comment by sebasira** [comment]
As for what I've read in the code, the `@Strategy` only uses the `Exchange` created by the `ExchangeFactory`. What I was thinking so I can use the WebSocket, is to define a very long rate (for example a day), and then override the **initialize()** method of the `@Strategy`, and create there the `StreamingExchange`, and whenever I receive an update call the same function **tickersUpdates(final Set<TickerDTO> tickers)**. Would that be a possible solution?

**Comment by straumat** [comment]
@sebasira why don't you use only one bot but with several strategies? That's what I do and it doesn't have any problem.

**Comment by sebasira** [comment]
Because I was thinking on having different instances of the bot for different accounts

**Comment by straumat** [comment]
different instances of the bot for different accounts for the same exchange you mean?

**Comment by sebasira** [comment]
Yes, I was thinking maybe my wife, my brothers and brother in law will use the same server. Each will have their own bot for their own accounts (not necessary the same Exchange, but the rate limit will be for the same Exchanges). Each instance will run as a separate application, in a different port with different `.properties` files.  As they are in the same server and rate limits applies to IP, it could be a problem. 

You get my idea?

**Comment by straumat** [comment]
@sebasira Yes, i will take some time to think about it !

**Comment by straumat** [comment]
@sebasira I checked things and it will change too many things (and won't work with all exchanges)... so I keep the idea but I won't make it soon... sorry !

**Comment by marstona** [comment]
polling... going back to the stone age

**Comment by straumat** [comment]
@marstona we try to be compatible with most exchanges
