### ISSUE TITLE
Update the Strategy on a BasicTa4jCassandreStrategy

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#794]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was thinking in the possibility of live-updating  the `Strategy` used by a `BasicTa4jCassandreStrategy`. In that class the `Strategy` is **final** so we can not update it.

I was thinking on removing that object:

```java
/** Ta4j Strategy. */
private final Strategy strategy;
```

and just call **getStrategy()** whenever I need to use it. This way I can have a live `Strategy` that I could update anytime I want, if for some reason I decide to. For example, I want to change the condition I set to enter/exit based on the market evolution.

I think that will give a lot of flexibility and I can perform live tweaking on the strategy.

**Describe alternatives you've considered**
One alternative I was going to test (but it's ugly considering what you already have done) is to have a **dumb** `Strategy` returned by the **getStrategy()** method and then call my **real** `Strategy` on every **tikcerUpdate**, when I detect a new `Bar` has been added to the `BarSeries`

**Additional context**
None

**Comment by sebasira** [comment]
If you want me to contribute with a PR about this, I'll be glad to do it

**Comment by straumat** [comment]
@sebasira Yes, indeed, no reason to be final! I would appreciate a PR! thx

**Comment by straumat** [comment]
@sebasira a new method has been added : `public void updateStrategy(final Strategy newStrategy)`
It allows you to update the executed ta4j strategy.
