### ISSUE TITLE
Is it possible to create an order for the quoteCurrency quantity?

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#795]
I was thinking in the **createBuyMarketOrder** where we specify the currencyPair and the amount of the base currency. But what about if I want to set the quote currency amount?

I mean, assume the pair is BTC/USDT and that I have 100 USDT in my account. I want to buy 100 USDT worth BTC. I don't care about how many BTC they are, I want to buy **all in**.

Would that be possible with the current state of this library?

**Comment by straumat** [comment]
@sebasira it's not possible right now but it's something I could develop yes

**Comment by xblaatx** [comment]
> I was thinking in the **createBuyMarketOrder** where we specify the currencyPair and the amount of the base currency. But what about if I want to set the quote currency amount?
> 
> I mean, assume the pair is BTC/USDT and that I have 100 USDT in my account. I want to buy 100 USDT worth BTC. I don't care about how many BTC they are, I want to buy **all in**.
> 
> Would that be possible with the current state of this library?

As workaround you can calculate in the onTickersUpdates() the amount BTC related to the latest price of BTC that came in with the last ticker.

`tickers.values().forEach(ticker -> {
            amountBtcFor1000Eur = BigDecimal.valueOf(1000).divide(ticker.getLast());
        });`

**Comment by straumat** [comment]
What bothers me for the moment is that, at the moment you create the order, I can't know exactly the price the exchange has. So I may order too much ... and fails on the position creation

**Comment by xblaatx** [comment]
> What bothers me for the moment is that, at the moment you create the order, I can't know exactly the price the exchange has. So I may order too much ... and fails on the position creation

Indeed. i've got errors to trying to make an order that exceeds my account funds.

**Comment by straumat** [comment]
@sebasira what do you think of having a helper method in the strategy that can tell you how much you can buy of an asset with another asset ? I prefer to leave the responsibility of the developer to choose an amount that does not risk to fail the position creation ?

**Comment by straumat** [comment]
A new method has been added to know how much you can buy of something:
```
    /**
     * Returns the amount of a currency I can buy with a certain amount of another currency.
     *
     * @param amountToUse amount you want to use buy the currency you want
     * @param currencyWanted the currency you want to buy
     * @return amount of currencyWanted you can buy with amountToUse
     */
    public final Optional<BigDecimal> getEstimatedBuyableAmount(final CurrencyAmountDTO amountToUse, final CurrencyDTO currencyWanted)
```
