### ISSUE TITLE
Make Repositories extends JpaSpecificationExecutor<> to be able to use Specifications for queries

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#833]
**Is your feature request related to a problem? Please describe.**
I would like to get all the `Positions` (opened, closed, both or with any condition) for a given `Strategy`. After taking a look to the `PositionRepository` I think that is not possible.

**Describe the solution you'd like**
A solution would be to make this `@Repository` (and why not all other `@Repository`) extend `JpaSpecificationExecutor`, like:

```java
@Repository
public interface PositionRepository extends JpaRepository<Position, Long>, JpaSpecificationExecutor<Position> {
```
This way anyone could create whatever query they want using `Specifications`, for example:

```java
List<Position> allPositionsOfStrategy = positionRepository.findAll(PositionSpecification.ofStrategyId(myStrategyId));

List<Position> allOpenedPositionsOfStrategy = positionRepository.findAll(PositionSpecification.ofStrategyId(myStrategyId).and(PositionSpecification.isOpen()));
```

The `PositionSpecification` should be created by the user according to their needs, but we could provide some basic `Specifications`

**Comment by straumat** [comment]
@sebasira i needed that to do some reporting so I add the positionService
```
    @Autowired
    private PositionService positionService;
```
Then, I can do: 
```
positionService.getPositions()
                .stream()
                .filter(p -> p.getStatus().equals(OPENED))
                .forEach(p -> emailBody.append("- ").append(p.getDescription()).append(System.lineSeparator()));
```
Wouldn't be easier ?

**Comment by sebasira** [comment]
Personally, I found it more easier to use the `Specification`... In first place because I do not play well with streams (lol), and second I think it would be more efficient in terms of DB, because it will only query the needed information.

But I don't think I'm the one to judge what's better and what's not.

**Comment by straumat** [comment]
@sebasira Ok i understand. I add JpaSpecificationExecutor to repository but I did not write test to validate it. I trust you :)

**Comment by sebasira** [comment]
Thanks! What kind of test you mean? Integration test or unit test?

I'm sorry I could not submit a PR for the other issues we were discussing. In addition to my recent "news", I've never work developing an auto-configuration and I would not like to be more a problem than a solution. But maybe I can help with test.

Tell me what would you need to test with this

**Comment by straumat** [comment]
@sebasira Hi! this has been merged so you can check if it works :) I'm not sure tests are necessary !
