### ISSUE TITLE
Question - Why Positions are updated on TikcerUpdates and not upon a newBar?

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#834]
I'm a total noob to trading... but one thing I always heard/read is:

> Wait for the *&%$ candle to close before taking action

And if I understood correctly, the `Strategy` check  the positions with every ticker update.

Let's assume we are using the **1h** interval for our `Strategy`, and we configure `TickerUpdates` every 30seconds. Would be correct to take actions before an hour? I know the price could fluctuate a lot between an hour, and maybe that could interfere with the strategy planned.

**Comment by straumat** [comment]
There are two different things. The method getDelayBetweenTwoBars tells Cassandre the time that has to pass before adding a new bar. You can set it, for example to one hour
And, if you setup in application.properties that want a ticker every second (ticker rate), the positions will be checked every second.

**Comment by sebasira** [comment]
Yes I think I understand that.

What confuses me is that there are some strategies/techniques that work on a certain "candle chart interval". I can think of one of the most popular like for example the 5min scalping.
If I'm correct (and remember I'm a noob to trading) that technique consist on watching the market evolution on the 5min candle chart. For that strategy it does not matter what happens in between the 5min, just the open and close prices. So for example I will set **getDelayBetweenTwoBars()** to 5min, but maybe I would like to get `TickerUpdates` every 30sec. So my `Strategy` should not be checked every 30sec, but every 5min. 

For example, I'm getting the `TickerUpdates` every 30sec, and if I understood correctly the `BasicTa4jCassandreStrategy` constructs the `BarSeries` with every `TickerUpdate` and I'm also using (or trying to use) that series to draw the chart with [ECharts](https://echarts.apache.org/en/index.html). Having the information every 30sec makes the candle look better with the peaks.

And what I think is the more relevant part in this discussion is that in the middle of the candle the market could take "any value" that can cause a `Position` to be closed (by winning or loosing) and maybe if we have waited for the candle to close, the decision would have been another

**Comment by sebasira** [comment]
I think I know where my confusion lies.... Re-reading the comment above I realize that I've said:

> So my `Strategy` should not be checked every 30sec, but every 5min.

The `Strategy` is indeed checked after a new `Bar` is created/added. The `Position` is what's checked every `TickerUpdate` not the `Strategy`.

I was thinking on **closing a Position** like a **exit Strategy**. But as I do not know much about trading I can not tell what is the best / common / preferred way.

Maybe you could enlighten me

**Comment by xblaatx** [comment]
@sebasira 

i will explain how i do this.

i write a good enter and exit strategy.
Then in shouldEnter() I create a position without a stopGainPercentage() rule. So only a stopLossPercentage() rule.
Then in shouldExit() I do something like this.

`positionService.getPositions().stream()
                .filter(position -> position.getStrategy().getId().equals(getStrategyDTO().getId()))
                .filter(position -> position.getStatus().equals(PositionStatusDTO.OPENED))
                .forEach(position -> {
                    positionService.forcePositionClosing(position.getId());
                });`

Explained in words. When the strategy sees a enter possibility it creates a position only with a stoploss rule. and when the strategy sees a exit possibility it search for all positions that are open for that strategy. and force closes it.

Somethimes this way of using a strategy gives me more then 15 % gain. and somethimes only 1% haha. But it is not a fixed number.

The reason i'm not using the stoploss rule from ta4j is because cassandre is not using the trading record from ta4j. So we cannot use that in these context.

**Comment by sebasira** [comment]
Thanks @xblaatx.

I was thinking in the opposite way, creating a `Position` without a stopLoss. Because with time and patience the market will always bounce back, so maybe no need to "loss" just wait to gain. What I like about your proposal is that the gain could be maximized, in mine, the gain is fixed (at the stopGain). And maybe also the `Strategy` without an **exitRule**

About the force closing... I remember expending some time analyzing if I should use `Position` with **forceClose** or just use raw **marketOrders**.

But anyway, I think we deviate a bit from the original question. But I think I can conclude that checking the `Position` at `TickerUpdates` or upon a new `Bar`, are different trading approaches and both are valid, depending on the needs.

**Comment by xblaatx** [comment]
> About the force closing... I remember expending some time analyzing if I should use Position with forceClose or just use raw marketOrders.

forceClose uses a marketOrder. 

> But anyway, I think we deviate a bit from the original question. But I think I can conclude that checking the Position at TickerUpdates or upon a new Bar, are different trading approaches and both are valid, depending on the needs.

indeed.

**Comment by straumat** [comment]
Can i close this issue or do you need more explanation?
