### ISSUE TITLE
CSV file for DryMode not found when executing from .jar

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#843]
**Release number**
v5.0.6

**Describe the bug**
I've created a `.jar` file and when executing it like

> java -jar test.jar

There's a log entry saying that the `user-trade.csv` file can not be found

```java
2021-12-04 21:58:43.194 ERROR 26366 --- [           main] t.c.t.b.util.dry.UserServiceDryModeAOP   : user-trade.csv not found !
```

I have no problem when debugging from the IDE. What's strange is that the file is present inside the `.jar` and I've also put it outside the `.jar`, in the same directoy

**To Reproduce**
I can only reproduce it when running the external jar

**Expected behavior**
I would expect the file to be picked up and the fake account will be configured

**Screenshots**
Here you can see the CSV inside the `.jar`
<img width="274" alt="Screen Shot 2021-12-04 at 19 04 20" src="https://user-images.githubusercontent.com/11217669/144725978-1ca9ecfc-e03e-4b5c-9fa8-2f8660c6e3c1.png">

**Comment by straumat** [comment]
@sebasira Hi ! why do you want to make a jar with those kinds of files included ?

**Comment by sebasira** [comment]
> @sebasira Hi ! why do you want to make a jar with those kinds of files included ?

I don't! I just want to make a `.jar` and test the **dry mode** in a cloud server. The problem is that the compiled `.jar` does not pickup the `.csv` so I try leaving it inside the jar (this setup is the one I have when debugging from the IDE, I have the `.csv` in the resource folder).

I also try with the `.csv` file outside the `.jar` next to it in the same directory but still it won't be picked up.

I'm thinking the **file path** could be the problem when loading the file with `Scanner`

**Comment by straumat** [comment]
@sebasira indeed, when making a jar, the files in src/test are not taken. Can you move your csv files to src/main/resources ?

**Comment by sebasira** [comment]
They are already at src/main/resources. 

From the screenshot of the first post, you can see that the the generate jar has the CSV

**Comment by sebasira** [comment]
I've try to add a log entry at the point where `Scanner` try to pick the file up, so I can log the file path, but I'm having trouble compiling the project. I'm used to gradle rather than maven.

**Comment by straumat** [comment]
@sebasira you can build and isntall cassandre release by typing: `mvn install -Dgpg.skip -DskipTests`

**Comment by straumat** [comment]
@sebasira did you have time to test ?

**Comment by straumat** [comment]
@sebasira can you tell me the command you used to create the jar ? Thx

**Comment by sebasira** [comment]
I'm sorry I do not know much about Maven and after executing the command you proposed:

> mvn install -Dgpg.skip -DskipTests

I add it to my project and all I get is an empty `.jar`

I can not build the project to test and work on it.

See:
<img width="701" alt="Screen Shot 2021-12-15 at 23 21 29" src="https://user-images.githubusercontent.com/11217669/146296190-dfa658ea-35cc-4fad-890b-8c90c6cb4b5f.png">

**Comment by straumat** [comment]
@sebasira i'm sorry. My question was, what command did you use to build your `test.jar` ?

**Comment by sebasira** [comment]
Oh I see!

I've built my app with gradle wrapper using

> ./gradlew build

**Comment by straumat** [comment]
@sebasira  did you try with this [https://stackoverflow.com/a/52404325](https://stackoverflow.com/a/52404325)

**Comment by sebasira** [comment]
I manage to build this project (maven) and use the `SNAPSHOT` version of Cassandre in my test app. I'll try with a log entry where `Scanner` looks for the file and get back in touch

**Comment by sebasira** [comment]
Well... I'm back...

After a lot and a lot and a lot of testing here's what I've found out:

1- I couldn't find (yet) a method that works for both: file in the **resource** folder and file outside the `.jar`, next to it.

2- The actual code:

```java
Scanner scanner = new Scanner(file.getFile())
```
 only works (at least for me) when debugging the app. I mean run it from the IDE (IntelliJ)

3- Replacing it with:

```java
Scanner scanner = new Scanner(file.getInputStream())
```

works with the complied `.jar` but only looks for the file `user-trade.csv` **inside the resource folder within the jar**

4- Using this other line:

```java
Scanner scanner = new Scanner(new FileReader(file.getFilename()))
```

Does not load the file inside the **resource** folder, but read the outer file, sitting next to the `.jar` file

At this point my idea is to:

- Try to load the file from outside the `.jar` according to **(4)**. If that fails because there's no file outside the `.jar` try looking for it inside the `.jar`, according to **(3)**. If that fails, then we can assure there's no file to be found

**Comment by straumat** [comment]
@sebasira don't you think the problem come from:
```
