### ISSUE TITLE
Can you support contract transactions?

### ISSUE THREAD

**Issue by hlevel** [cassandre-tech/cassandre-trading-bot#859]
Hello, there are already projects to realize contract transactions for xchange. Would you consider accessing it? Reference address https://github.com/pwn2ownYearn/algowin-api

**Comment by straumat** [comment]
@hlevel Hi, sorry i don't speak chinese. Can you tell what is contact transactions ? I don't know about it

**Comment by hlevel** [comment]
Hello, author
The xchange framework does not support coin standard and u standard trading, as well as futures trading. This is an extension implementation project to realize additional functions.

**Comment by straumat** [comment]
@hlevel Hi, i will try to take a look at future but I don'tr know exactly how it works so it will take time

**Comment by straumat** [comment]
@hlevel ok it seems quite a lot of work :) I closed the issue and add your idea to the roadmap. I will contact you when I start to work on it.

**Comment by hlevel** [comment]
OK, thank you for your consideration!
