### ISSUE TITLE
Error reading display of back test time zone.

### ISSUE THREAD

**Issue by hlevel** [cassandre-tech/cassandre-trading-bot#884]
Hi, make a small suggestion to solve the project better
`v5.0.7`

step1: The system sets the time zone to `Asia/Shanghai`
step2: Original data `1642608000` ,This value is read out after saving to the database, Eight extra hours:
`timestamp="2022-01-20T08:00+08:00[Asia/Shanghai]"`

Actual time:
`timestamp="2022-01-20T00:00+08:00[Asia/Shanghai]"`

Solution:
`spring.jpa.properties.hibernate.jdbc.time_zone = UTC`

**Comment by straumat** [comment]
@hlevel in fact, from what I understand each user should set its own `spring.jpa.properties.hibernate.jdbc.time_zone` to the same timezone of the files he downloaded. Am I right ?

**Comment by hlevel** [comment]
@straumat I personally suggest that the project should have its own time setting parameters and avoid solving them with other framework settings, such as `cassandre.trading.bot.timezone=Asia/Shanghai`

**Comment by straumat** [comment]
@hlevel I apreciate your idea but from what I read on forums, it should be the user of the program who set the right time zone in configuration as we are doing in Docker.
