### ISSUE TITLE
Index ta4j BarSeries problem

### ISSUE THREAD

**Issue by hlevel** [cassandre-tech/cassandre-trading-bot#885]
Hi, I found a problem through the back test. The prices in the BarSeries class are all the same. And I didn't set it.

My code:
```
public class ScplpingEngulfStrategy extends BasicTa4jCassandreStrategy {
    @Override
    public CurrencyPairDTO getRequestedCurrencyPair() {
        return new CurrencyPairDTO(XRP, USDT);
    }

    @Override
    public int getMaximumBarCount() {
        return 10;
    }

    @Override
    public Duration getDelayBetweenTwoBars() {
        return Duration.ofMinutes(1);
    }

    @Override
    public Strategy getStrategy() {
        BullishEngulfingIndicator bullishEngulfing = new BullishEngulfingIndicator(getSeries());
        BearishEngulfingIndicator bearishEngulfing = new BearishEngulfingIndicator(getSeries());

        Rule entryRule = new BooleanIndicatorRule(bullishEngulfing);
        Rule exitRule = new BooleanIndicatorRule(bearishEngulfing);

        return new BaseStrategy(entryRule, exitRule);
    }

    @Override
    public void shouldEnter() {
        if (canBuy(new BigDecimal("900"))) {
            System.out.println("shouldEnter");
            // Create rules.
            PositionRulesDTO rules = PositionRulesDTO
                    .builder()
                    .stopGainPercentage(0.5f)
                    .stopLossPercentage(0.5f)
                    .build();
            // Create position.
            createLongPosition(
                    new CurrencyPairDTO(XRP, USDT),
                    new BigDecimal("900"),
                    rules);
        }
    }

    @Override
    public void shouldExit() {
        System.out.println("shouldExit");

    }

    @Override
    public Optional<AccountDTO> getTradeAccount(Set<AccountDTO> accounts) {
        // From all the accounts we have on the exchange, we must return the one we use for trading.
        if (accounts.size() == 1) {
            return accounts.stream().findAny();
        }

        return accounts.stream()
                .filter(a -> "trade".equals(a.getName()))
                .findFirst();
    }

    @Override
    public void onTickersUpdates(Map<CurrencyPairDTO, TickerDTO> tickers) {
        TickerDTO ticker = tickers.get(this.getRequestedCurrencyPair());
        //System.out.println(ticker.getTimestamp().toEpochSecond() + "\t" + ticker.getOpen() + "\t" + ticker.getLast() + "\t" + ticker.getHigh() + "\t" + ticker.getLow());
    }
```

The debugging process is very clear. You can see the closing price. Please see the attached picture,I wrote a JUnit to verify, The results are also attached.

Junit code:
```
    @Test
    public void bullishEngulfingTest(){
        // Creating a time series (from any provider: CSV, web service, etc.)
        BarSeries series = new BaseBarSeriesBuilder().withName("AXP_Stock").build();
        // adding open, high, low, close and volume data to the series
        series.addBar(ZonedDateTime.now(), 0.73993, 0.74001, 0.73938, 0.73951, 95754.06624465);
        series.addBar(ZonedDateTime.now().plusMinutes(1), 0.73817, 0.73917, 0.73707, 0.73717, 51330.41261578);
        series.addBar(ZonedDateTime.now().plusMinutes(2), 0.73626, 0.74001, 0.73525, 0.73996, 28020.35480699);
        series.addBar(ZonedDateTime.now().plusMinutes(3), 0.73931, 0.73997, 0.73865, 0.73987, 23961.6403);

        // Getting the close price of the ticks
        Bar firstBar = series.getBar(0);
        Num firstClosePrice = firstBar.getClosePrice();
        System.out.println("First close price: " + firstClosePrice.doubleValue());

        // Or within an indicator:
        //ClosePriceIndicator closePrice = new ClosePriceIndicator(series);
        BullishEngulfingIndicator bullishEngulfing = new BullishEngulfingIndicator(series);
        BearishEngulfingIndicator bearishEngulfing = new BearishEngulfingIndicator(series);

        Rule entryRule = new BooleanIndicatorRule(bullishEngulfing);
        Rule exitRule = new BooleanIndicatorRule(bearishEngulfing);

        Strategy strategy = new BaseStrategy(entryRule, exitRule);

        // Running our juicy trading strategy...
        BarSeriesManager manager = new BarSeriesManager(series);
        TradingRecord tradingRecord = manager.run(strategy);
        System.out.println("Number of trades for our strategy: " + tradingRecord.getPositionCount());
    }
```

[file_info.zip](https://github.com/cassandre-tech/cassandre-trading-bot/files/7904676/file_info.zip)

**Comment by straumat** [comment]
@hlevel i'm not sure to see where the problem is? It seems the data are wrong in your code and not in mine ? Can you tell me more. Thank you !

**Comment by hlevel** [comment]
@straumat Do you mean that your code does not reproduce this problem?

`this.ctx = new BarContext(this.duration, timestamp, latestPrice, latestPrice, latestPrice, latestPrice, 0);`

Take a look at this method. It is required to pass the highest, lowest, opening and closing price. Here, only the closing price is passed

![image](https://oscimg.oschina.net/oscnet/up-5489997bc8ecf8c8471115ac280a17a21e9.jpg)

**Comment by straumat** [comment]
@hlevel ah you are right... it's not me who wrote this code, have to see why this happened. You seem right, I will fix this

**Comment by straumat** [comment]
@xblaatx do you have an idea?

**Comment by straumat** [comment]
@hlevel Hi... while refactoring my code, i think i should focus on cassandre internal beahvioir and extensibility (API and others...). I plan to remove ta4J support and let community create their own code. Would you be interested in creating a ta4J strategy project for Cassandre on top of cassande and maintain it ? I would advertise your project on Cassandre web site

**Comment by hlevel** [comment]
@straumat Hi. Do you want me to solve ta4j this current problem?
Your current BasicTa4jCassandreStrategy has poor performance. only single currency is supported. 
This can only keep the opportunity. You can't take the initiative to find trading opportunities in each currency.
In fact, I built a multi currency indicator class locally based on Cassandre strategy It can help find more currency opportunities. It is not perfect and needs to be refined。
I will contribute when it is improved.

**Comment by straumat** [comment]
@hlevel not exactly. I was thinking about removing Ta4J from Cassandre and, to remove BasicTa4JCassandreStrategy. Cassandre would only manage strategy. If you like it, you could create a new github project that extends Cassandre strategy to better support ta4J ? It would be an independent project I would promote on cassandre website.
This way, I could concentrate on other things and not have to do the ta4J support

**Comment by hlevel** [comment]
@straumat You can start your refactoring work. I need ta4j I'll expand.

**Comment by petrmac** [comment]
@hlevel, I am willing to help. I was looking into ta4j strategy issues as well some time ago, but eventually had not enough capacity to finish that myself. If you are starting a new project on GitHub, please let me know. We can discuss on discord what needs to be done and approach…

**Comment by straumat** [comment]
@petrmac You can make an announcement on the discord! I can also talk about your project on cassandre web site
