### ISSUE TITLE
Auto-configuration module should not have a SpringBootApplication

### ISSUE THREAD

**Issue by snicoll** [cassandre-tech/cassandre-trading-bot#91]
The auto-configuration module has a `@SpringBootApplication`. That looks really odd to me considering an auto-configuration module is supposed to be added to an existing infrastructure. If you want users to easily get started, this app should probably move elsewhere.

**Comment by straumat** [comment]
I removed the @SpringBootApplication class from the project and moved it to the tests

[https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/trading-bot-spring-boot-autoconfigure/src/test/java/tech/cassandre/trading/bot/CassandreTradingBot.java](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/trading-bot-spring-boot-autoconfigure/src/test/java/tech/cassandre/trading/bot/CassandreTradingBot.java)

**Comment by snicoll** [comment]
For the reference, If you're doing this to get a context for your tests, it doesn't have to be a `@SpringBootApplication` (quite misleading IMO). `@SpringBootConfiguration` [is enough](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-testing-spring-boot-applications-detecting-config) and you could rename the class accordingly.
