### ISSUE TITLE
A standard starter should at least bring "spring-boot-starter"

### ISSUE THREAD

**Issue by snicoll** [cassandre-tech/cassandre-trading-bot#92]
See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-module-starter

**Comment by straumat** [comment]
I added 
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter</artifactId>
</dependency>
```
To my starter 

[https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/trading-bot-spring-boot-starter/pom.xml](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/trading-bot-spring-boot-starter/pom.xml)
