### ISSUE TITLE
Please add lombok to mvn

### ISSUE THREAD

**Issue by Freeongoo** [cassandre-tech/cassandre-trading-bot#937]
when starting the project and opening the sources, it swears that there is no lombok library. Add it to the repository so that you can more conveniently look at the sources

**Comment by straumat** [comment]
@Freeongoo can you give me more details on the error please?
When I download the sources from scratch and run maven, everything seems to work correctly and when using Intellij, I also don't see any problem.

**Comment by Freeongoo** [comment]
@straumat very strange, because when I get all the repositories by mvn and started going into the sources of this project, then  lombok annotations were indicated as an unknown library

**Comment by straumat** [comment]
@Freeongoo strange... can I close the issue ?

**Comment by Freeongoo** [comment]
@straumat yes you can. I solved this problem by adding lombok dependency to the project
