### ISSUE TITLE
add mysql database support

### ISSUE THREAD

**Issue by Freeongoo** [cassandre-tech/cassandre-trading-bot#939]
since in this project it is theoretically possible to connect to any type of relational database, since any driver can be specified in the connection. But the problem is that for MySQL the migration falls on an exception:

```
6 changes have validation failures
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
     columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
```

**Comment by straumat** [comment]
@Freeongoo I know and i'm having  real problem with that, I think I can't fix it for the moment.
I don't know if your familiar with liquidbase but liquidbase stores an sha of each change. This means I can't change older migration script I created or no migration will every work :( If you have an idea...

**Comment by Freeongoo** [comment]
@straumat theoretically, you can make changes to migrations so that they do not affect existing ones, simply by ignoring the code hash check:

```
<changeSet author="auth" id="1">
    <validCheckSum>ANY</validCheckSum>
```

further separating specific migrations indicating for which type of database to apply:

`dbms="mysql"`

if it’s quite simple, then for all existing migrations indicate that this is only for postgresql and add migrations for mysql only

**Comment by Freeongoo** [comment]
@straumat yes, this is the only way not to break existing migrations.

**Comment by Freeongoo** [comment]
@straumat cool! Thx.

**Comment by ricardo-zenki** [comment]
Hello, I am having this issue... do I have to change anything in my configuration to avoid the error? Thanks!
