### ISSUE TITLE
Is it possible to somehow prohibit opening two or more positions in parallel?

### ISSUE THREAD

**Issue by Freeongoo** [cassandre-tech/cassandre-trading-bot#945]
When testing, I often noticed that a situation is possible when two or more positions are opened in parallel. Is it possible to somehow configure so that another position is not opened if there is already one active within the same strategy?

**Comment by straumat** [comment]
@Freeongoo The best way is to add this method inside your strategy:
```
    private boolean hasAlreadyAnOpenedPosition() {
        return getPositions().values().stream().anyMatch(positionDTO -> positionDTO.getStatus().equals(OPENED));
    }
```

**Comment by Freeongoo** [comment]
@straumat yes, I think it's better to do the check already in my strategy, thanks!
