### ISSUE TITLE
Is it possible to buy a long position on a limit order

### ISSUE THREAD

**Issue by Freeongoo** [cassandre-tech/cassandre-trading-bot#951]
As far as I understand, the PositionService.createLongPosition method performs a buy on the market, which is not entirely suitable in some situations, especially when the price changes rapidly.

1. Is there an implementation of buying a long position on a limit order?
2. and I still do not quite understand how the sale is performed when a certain price is reached? Also on a market order? or by take-profit or stop-loss via api?

**Comment by straumat** [comment]
@Freeongoo 
1- Nope.
2- When a ticker arrives with a price corresponding to the position rulses you setup, Cassandre automatically issue a market order

**Comment by Freeongoo** [comment]
@straumat thanks I got it.
