### ISSUE TITLE
How to add a new CurrencyDTO

### ISSUE THREAD

**Issue by Freeongoo** [cassandre-tech/cassandre-trading-bot#955]
How to add a new CurrencyDTO, like 'SOL' or 'ZIL'? 
since they are in kucoin but not in this DTO, is it allowed to add new ones or is this not provided for?

**Comment by straumat** [comment]
@Freeongoo just do `private static final CurrencyDTO SOL = new CurrencyDTO("SOL");`
You can also create a merge request to add it to our constants.

**Comment by straumat** [comment]
@Freeongoo  if it works, you can close ? thx
