### ISSUE TITLE
Questions about strategy set up with custom indicators

### ISSUE THREAD

**Issue by sjarrin** [cassandre-tech/cassandre-trading-bot#956]
Hi, 

First, thanks a lot for this wonderful job.

Here is my problem: I'm writing a strategy where positions exit and stop loss prices are precisely calculated when opening the position by custom indicators I wrote.
Doing that I'm facing some difficulties to write it, maybe due to the fact that I don't know the project very well and I did not find answer in the documentation.

Here are my questions:
- I'd like to know if it was possible to use prices instead of percentages in PositionRulesDTO ? Because, as I was explaining before, my strategy relies on prices and not percentages, so it would be more convenient to also be able to define exit and stop loss using prices
- If it's not possible, what should be the best option ? To directly create orders, as mentioned here: https://trading-bot.cassandre.tech/learn/technical-analysis.html#react-to-signals ?
- Is it possible to access in the shouldEnter() method indicators that are already computed in the getStrategy() method ? As prices are defined using these custom indicators, I'd need to access them and would avoid to recompute them each time shouldEnter method is executed
- Is it possible to use the same strategy for both long and short positions ? Because I've seen such limitation in ta4j (https://ta4j.github.io/ta4j-wiki/FAQ.html) and was wondering if Cassandre was impacted.

Thanks in advance for your help.

**Comment by straumat** [comment]
Thx @sjarrin !!!
Nope, I did not yet developed rules based on amount :( so the best option is indeed to create orders directly yes. Depending on your exchange, you can create limit order so it would automatically be sold and the price you calculated. You can do that with long and short
