### ISSUE TITLE
Give your own price to the createShortPosition & createLongPosition

### ISSUE THREAD

**Issue by AukeRoze** [cassandre-tech/cassandre-trading-bot#967]
At the moment it is not possible to give your own price to this function (createShortPosition  & createLongPosition). Sometimes you want to place a long position at a different price at a certain point in time.

**Comment by straumat** [comment]
@AukeRoze when you create a position, it creates an order immediately. This is how I get the price. If you set the price yourself, the gains and rules calculated may be different from reality no ?

**Comment by straumat** [comment]
Automatically closing issue (1 month inactivity)
