### ISSUE TITLE
Any refactoring idea to achieve regular stocks trading?

### ISSUE THREAD

**Issue by mujicadiazr** [cassandre-tech/cassandre-trading-bot#970]
Hi @straumat 

First of all, thanks for such a great solution! :1st_place_medal:  The business domain design is really solid, also the Reactive Programming part, and overall a great solution in general.

Since I'm not yet into crypto, I'd like to adapt it to trade regular stocks where many crypto concepts like `CurrencyPairDTO` don't apply.

What would be the best refactoring approach to achieve this?
Thanks in advance!

**Comment by straumat** [comment]
@mujicadiazr thanks a lot :)
From my point of view, I would create something call `Instrument` that looks similar to `CurrencyPairDTO` that will be used as argument everywhere. XChange has done it. It should work in a similar way. Then, you have to implement the service here : [services](https://github.com/cassandre-tech/cassandre-trading-bot/tree/development/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service) with a regular stocks services

**Comment by mujicadiazr** [comment]
@straumat Thanks for your answer.
 Yeah, that's what I was thinking. Is there any other critical business concept that is coupled to crypto?

**Comment by straumat** [comment]
@mujicadiazr with crypto, when you start, the balance API will return for example that you own 1000 USDT. If you buy some bitcoin, the balance API will return your USDT amount and your bitcoin amount which allows me to implement canBuy() and canSell() methods. With other systems, maybe you have another API to call to know all the assets you have (other than balance API).
Aside from that, I don't think it's very different

**Comment by mujicadiazr** [comment]
I think most of the business logic is equivalent to regular Stocks Exchanges, I just wanted to isolate everything is `crypto-related `so I have a good picture of what is needed. For regular Stocks Brokers there is definitely a Balance API to query your balance.
