### ISSUE TITLE
Liquibase migration fails with MySQL 8.0.27 Database

### ISSUE THREAD

**Issue by ricardo-zenki** [cassandre-tech/cassandre-trading-bot#995]
**Release number**
5.0.8 & 6.0.0

**Describe the bug**

I am getting an error with liquibase migration, it seems that it requires additional information inside the migration script in order to work properly with MySQL:

`
2022-05-26 19:40:03,796 WARN  [main] org.springframework.context.support.AbstractApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:
     6 changes have validation failures
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
          columnDataType is required for renameColumn on mysql, db/changelog/db.changelog-4.1.0.xml::changelog-4.1.0::straumat
`

**To Reproduce**
Configure Spring datasource to use a MySQL 8.0.27 database.

**Additional context**
Database Version: MySQL 8.0.27

**Comment by ricardo-zenki** [comment]
I just take a look into the db/changelog/db.changelog-4.1.0.xml file and it contains the columnDataType for each renameColumn, I was looking for other causes/solutions in stackoverflow but unfortunately I haven't luck.

**Comment by straumat** [comment]
@ricardo-zenki I will investigate this. Indeed, before we had an issue because columnDataType was not set but it is supposed to be fixed with this : https://github.com/cassandre-tech/cassandre-trading-bot/issues/939
